# Generated by Django 6.0.7 on 2026-08-26 13:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('list_invite', 'Convite para lista'), ('account_deletion', 'Conta agendada para deleção')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at', 'expires_at'], name='notif_user_unread_idx')],
            },
        ),
    ]
