# Generated by Django 6.0.7 on 2026-08-26 14:31

import django.db.models.deletion
import django.utils.timezone
import secrets
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('normalized_name', models.CharField(editable=False, max_length=160, unique=True)),
                ('tax_id', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AdministrativeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(max_length=64)),
                ('target_type', models.CharField(max_length=32)),
                ('target_id', models.UUIDField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administrative_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('address', models.CharField(max_length=300)),
                ('normalized_address', models.CharField(editable=False, max_length=300)),
                ('external_place_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='shopping.marketnetwork')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('gtin', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(editable=False, max_length=200)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('variant', models.CharField(blank=True, max_length=120)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('normalized_name', 'brand', 'variant', 'quantity', 'unit'), name='product_fingerprint_unique')],
            },
        ),
        migrations.CreateModel(
            name='PriceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observed_on', models.DateField()),
                ('is_valid', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_observations', to='shopping.marketbranch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_observations', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_observations', to='shopping.product')),
            ],
            options={
                'ordering': ['-observed_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('alias', models.CharField(max_length=200)),
                ('normalized_alias', models.CharField(editable=False, max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='shopping.product')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('regular_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('promotional_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('is_valid', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='shopping.marketbranch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to=settings.AUTH_USER_MODEL)),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='shopping.marketnetwork')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='shopping.product')),
            ],
            options={
                'ordering': ['ends_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('target_type', models.CharField(max_length=32)),
                ('target_id', models.UUIDField()),
                ('reason', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=12)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('resource_type', models.CharField(choices=[('product', 'Product'), ('price', 'Price'), ('promotion', 'Promotion'), ('market', 'Market'), ('location', 'Location')], max_length=16)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('location', models.JSONField(blank=True, default=dict)),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_memberships', to=settings.AUTH_USER_MODEL)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='shopping.shoppinglist')),
            ],
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(max_length=16)),
                ('is_checked', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('purchased_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.shoppinglist')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('invited_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_list_invites', to=settings.AUTH_USER_MODEL)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='shopping.shoppinglist')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('purchased_on', models.DateField(default=django.utils.timezone.localdate)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=13)),
                ('client_operation_id', models.UUIDField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shopping_purchases', to='shopping.marketbranch')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shopping_purchases', to='shopping.shoppinglist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('list_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='shopping.listitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shopping.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shopping.shoppingpurchase')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('current_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_updated_at', models.DateTimeField(blank=True, null=True)),
                ('list_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_items', to='shopping.listitem')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_items', to='shopping.store')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=5, max_digits=13)),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('purchased_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('store_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='shopping.storeitem')),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('device_id', models.UUIDField()),
                ('client_operation_id', models.UUIDField()),
                ('entity_type', models.CharField(max_length=64)),
                ('operation_type', models.CharField(max_length=16)),
                ('payload_hash', models.CharField(max_length=64)),
                ('base_version', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('conflict', 'Conflict')], default='confirmed', max_length=12)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_operations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_markets', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='shopping.marketbranch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'branch'), name='favorite_market_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='marketbranch',
            constraint=models.UniqueConstraint(fields=('network', 'normalized_address'), name='market_branch_address_unique'),
        ),
        migrations.AddIndex(
            model_name='priceobservation',
            index=models.Index(fields=['product', 'branch', 'observed_on'], name='shopping_pr_product_a5c711_idx'),
        ),
        migrations.AddConstraint(
            model_name='priceobservation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='price_observation_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='productalias',
            constraint=models.UniqueConstraint(fields=('product', 'normalized_alias'), name='product_alias_unique'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='promotion_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('promotional_price__lt', models.F('regular_price'))), name='promotion_price_lower'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('network__isnull', False), ('branch__isnull', False), _connector='OR'), name='promotion_scope_required'),
        ),
        migrations.AddConstraint(
            model_name='listmembership',
            constraint=models.UniqueConstraint(fields=('shopping_list', 'user'), name='shopping_list_user_unique'),
        ),
        migrations.AddConstraint(
            model_name='listmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'owner')), fields=('shopping_list',), name='shopping_list_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='listitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='shopping_item_quantity_positive'),
        ),
        migrations.AddIndex(
            model_name='listinvite',
            index=models.Index(fields=['token'], name='shopping_li_token_4f7a71_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppingpurchase',
            index=models.Index(fields=['user', 'branch', 'purchased_on'], name='shopping_sh_user_id_8d8daa_idx'),
        ),
        migrations.AddConstraint(
            model_name='shoppingpurchase',
            constraint=models.UniqueConstraint(fields=('user', 'client_operation_id'), name='shopping_purchase_operation_unique'),
        ),
        migrations.AddConstraint(
            model_name='shoppingpurchaseitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='shoppingpurchaseitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='purchase_item_unit_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='storeitem',
            constraint=models.UniqueConstraint(fields=('list_item', 'store'), name='shopping_list_item_store_unique'),
        ),
        migrations.AddConstraint(
            model_name='storeitem',
            constraint=models.CheckConstraint(condition=models.Q(('current_unit_price__gte', 0), ('current_unit_price__isnull', True), _connector='OR'), name='shopping_store_item_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='shopping_purchase_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='shopping_purchase_unit_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='shopping_purchase_total_price_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='syncoperation',
            index=models.Index(fields=['user', 'device_id', 'received_at'], name='shopping_sy_user_id_02edf9_idx'),
        ),
        migrations.AddConstraint(
            model_name='syncoperation',
            constraint=models.UniqueConstraint(fields=('user', 'client_operation_id'), name='sync_operation_user_unique'),
        ),
    ]
