# Generated by Django 6.0.7 on 2026-08-26 20:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_purchasechange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='void_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='purchase',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ListOwnershipChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='updated at')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('new_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_list_ownerships', to=settings.AUTH_USER_MODEL)),
                ('previous_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferred_list_ownerships', to=settings.AUTH_USER_MODEL)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_changes', to='shopping.shoppinglist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
