# Generated by Django 6.0.7 on 2026-08-27 18:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_remove_listinvite_shopping_li_token_4f7a71_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='listitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
