# Generated by Django 6.0.7 on 2026-08-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_purchase_void_reason_purchase_voided_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketbranch',
            options={'verbose_name': 'Unidade cadastrada', 'verbose_name_plural': 'Unidades cadastradas'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchased_at'], 'verbose_name': 'Compra de item', 'verbose_name_plural': 'Compras de itens'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['name'], 'verbose_name': 'Mercado salvo', 'verbose_name_plural': 'Mercados salvos'},
        ),
    ]
