# Generated by Django 6.0.7 on 2026-08-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopping", "0005_backfill_purchase_change_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingpurchase",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="shopping_purchases",
                to="shopping.marketbranch",
            ),
        ),
    ]
